import { execFile } from 'node:child_process'
import { mkdir, readdir, readFile, realpath, writeFile } from 'node:fs/promises'
import { basename, dirname, join, relative } from 'node:path'
import { promisify } from 'node:util'
import { MouseButton, type ClickOpts, type PageSession, type Point, type Rect } from '../cdp/types.js'
import { locatorFromArgs } from './locator.js'
import { AGENT_VIEW_DIR } from './port.js'

/** How a replay finds a control again: its test id, else role + name. */
export type StepTarget = { testid?: string; role: string; name: string }

/** A drop target: a row, or any element by its test id. */
export type DropTarget = StepTarget | { testid: string }

/** Click ops of the step protocol and the pointer each one sends. */
export const CLICKS = {
  click: {},
  dblclick: { clicks: 2 },
  rightclick: { button: MouseButton.Right },
} as const satisfies Record<string, ClickOpts>
export type ClickOp = keyof typeof CLICKS

export const isClickOp = (op: string): op is ClickOp => Object.keys(CLICKS).includes(op)

export type RecordedStep =
  | { op: ClickOp | 'type' | 'select'; target: StepTarget; value?: string; isPassword: boolean }
  | { op: 'scroll'; direction: 'up' | 'down' }
  /** `to`: a row, any element by test id, or absent = the viewport. */
  | { op: 'drag'; target: StepTarget; to?: DropTarget; edge: Edge }

export type UntilArgs = { testid?: string; selector?: string }

export type ActScript = {
  until: UntilArgs
  steps: RecordedStep[]
  note?: string
  /** Where the recording began: hash route, else path + query. Informational; replay does not navigate. */
  start?: string
  /** Script replayed first unless its own until already holds (a login). */
  after?: string
}

const execFileAsync = promisify(execFile)
/** The old global pile: still read when a name is missing from the project store, never written. */
const LEGACY_DIR = join(AGENT_VIEW_DIR, 'scratch')
const INDEX_HEADER = '# act scripts: generated by agent-view on every save. Replay one with `agent-view act replay <name>`.'

export const isScriptName = (name: string | undefined): name is string => !!name && /^[\w.-]+$/.test(name)

/** `${NAME}` in a saved string: an env var of that name, substituted at replay. */
const PLACEHOLDER = /\$\{([A-Z][A-Z0-9_]*)\}/g
const PARAM_ARG = /^([A-Z][A-Z0-9_]*)=(.+)$/s
/** Protocol words: never a parameter, so a value that happens to equal `click` stays an op. */
const FIXED_KEYS = new Set(['op', 'role', 'edge', 'direction'])

/** Every string replay matches or types: test ids, names, typed text, the until. */
function mapStrings<T>(value: T, fn: (s: string) => string): T {
  if (typeof value === 'string') return fn(value) as T
  if (Array.isArray(value)) return value.map(v => mapStrings(v, fn)) as T
  if (!value || typeof value !== 'object') return value
  return Object.fromEntries(Object.entries(value).map(([k, v]) => [k, FIXED_KEYS.has(k) ? v : mapStrings(v, fn)])) as T
}

const mapScript = (script: ActScript, fn: (s: string) => string): ActScript =>
  ({ ...script, until: mapStrings(script.until, fn), steps: mapStrings(script.steps, fn) })

/**
 * `--param NAME=value` at save: every occurrence of the value becomes `${NAME}`, longest value
 * first so one that contains another is not split. A value found nowhere is an error, not a no-op.
 */
export function markParams(script: ActScript, params: string[]): ActScript | { error: string } {
  const pairs: [string, string][] = []
  for (const param of params) {
    const match = PARAM_ARG.exec(param)
    if (!match) return { error: `--param ${param} — NAME=value, NAME of A-Z 0-9 _` }
    pairs.push([match[1], match[2]])
  }
  let marked = script
  for (const [name, value] of pairs.sort((a, b) => b[1].length - a[1].length)) {
    let isFound = false
    marked = mapScript(marked, s => {
      if (!s.includes(value)) return s
      isFound = true
      return s.split(value).join(`\${${name}}`)
    })
    if (!isFound) return { error: `--param ${name}: "${value}" is in no step and not in the until` }
  }
  return marked
}

/** Parameter names a script needs, sorted. */
export function paramsOf(script: ActScript): string[] {
  const names = new Set<string>()
  mapScript(script, s => {
    for (const m of s.matchAll(PLACEHOLDER)) names.add(m[1])
    return s
  })
  return [...names].sort()
}

/** Placeholders replaced by `values`; call only once `paramsOf` is covered. */
export const fillParams = (script: ActScript, values: Record<string, string>): ActScript =>
  mapScript(script, s => s.replace(PLACEHOLDER, (m, name: string) => values[name] ?? m))

/**
 * `<main checkout>/<rel>/.agent-view/scripts`, `rel` being where the project sits in its
 * checkout: every git worktree of a project shares the main checkout's store, so a script
 * recorded on one branch is found on all. Outside git, the project dir itself.
 */
export async function scriptStore(projectDir: string): Promise<string> {
  const dir = await realpath(projectDir)
  const args = ['rev-parse', '--path-format=absolute', '--git-common-dir', '--show-toplevel']
  const root = await execFileAsync('git', args, { cwd: dir, windowsHide: true }).then(
    ({ stdout }) => {
      const [commonDir, toplevel] = stdout.trim().split(/\r?\n/)
      // A submodule's common dir sits in the superproject's .git/modules: it has no main checkout of its own.
      const main = basename(commonDir) === '.git' ? dirname(commonDir) : toplevel
      return join(main, relative(toplevel, dir))
    },
    () => dir,
  )
  return join(root, '.agent-view', 'scripts')
}

/** Steps are stored by what identifies a control across runs, never by row number. Passwords are not stored. */
export async function writeScript(store: string, name: string, script: ActScript): Promise<string> {
  await mkdir(store, { recursive: true })
  const steps = script.steps.map(s => ('isPassword' in s && s.isPassword ? { ...s, value: undefined } : s))
  const path = join(store, `${name}.json`)
  await writeFile(path, JSON.stringify({ ...script, steps }, null, 1))
  await writeFile(join(store, 'INDEX.md'), `${INDEX_HEADER}\n\n${renderScripts(await listScripts(store))}\n`)
  return path
}

export async function readScript(store: string, name: string): Promise<ActScript | undefined> {
  for (const dir of [store, LEGACY_DIR]) {
    try {
      return JSON.parse(await readFile(join(dir, `${name}.json`), 'utf8')) as ActScript
    } catch { /* next */ }
  }
  return undefined
}

/** Every script in the store, by name, so a shared prefix (`settings-*`) groups a UI section. */
export async function listScripts(store: string): Promise<[string, ActScript][]> {
  const files = await readdir(store).catch(() => [])
  const names = files.filter(f => f.endsWith('.json')).map(f => f.slice(0, -'.json'.length)).sort()
  const entries = await Promise.all(names.map(async name => [name, await readScript(store, name)] as const))
  return entries.filter((e): e is [string, ActScript] => e[1] !== undefined)
}

export const renderScripts = (entries: [string, ActScript][]): string => entries.map(([name, s]) => {
  const parts = [
    s.note,
    s.start && `start \`${s.start}\``,
    s.after && `after \`${s.after}\``,
    paramsOf(s).length && `params ${paramsOf(s).join(' ')}`,
    `until ${locatorFromArgs(s.until)?.label}`,
    `${s.steps.length} step${s.steps.length === 1 ? '' : 's'}`,
  ]
  return `- \`${name}\` — ${parts.filter(Boolean).join(' · ')}`
}).join('\n')

export const EDGES = ['left', 'right', 'top', 'bottom', 'center'] as const
export type Edge = typeof EDGES[number]
/** Deepest a drop point sits inside an edge; split zones along a widget edge are ~60 px strips. */
const EDGE_INSET_PX = 20

export const isEdge = (value: string): value is Edge => (EDGES as readonly string[]).includes(value)

/** Drop point inside `box`, on its midline, inset from `edge` — a centre drop replaces instead of splitting. */
export function edgePoint(box: Rect, edge: Edge): Point {
  const cx = box.x + box.width / 2
  const cy = box.y + box.height / 2
  const insetX = Math.min(EDGE_INSET_PX, box.width / 4)
  const insetY = Math.min(EDGE_INSET_PX, box.height / 4)
  if (edge === 'left') return { x: box.x + insetX, y: cy }
  if (edge === 'right') return { x: box.x + box.width - insetX, y: cy }
  if (edge === 'top') return { x: cx, y: box.y + insetY }
  if (edge === 'bottom') return { x: cx, y: box.y + box.height - insetY }
  return { x: cx, y: cy }
}

export async function viewportBox(conn: PageSession): Promise<Rect> {
  const { viewport } = await conn.getLayoutSnapshot()
  return { x: 0, y: 0, ...viewport }
}
